packages:
  - apps/*
  - packages/*
  - evals
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - eslint@10.12.0
  - '@modelcontextprotocol/client@2.3.0'
  - '@modelcontextprotocol/core@2.3.0'
  - '@modelcontextprotocol/fastify@2.0.1'
  - '@modelcontextprotocol/node@2.1.1'
  - '@modelcontextprotocol/server@2.3.0'
  - pino@10.4.0
